# GitHub Build workflow.
# Builds and tests the system.
name: Build

on:
  # Execute when any branch is pushed to.
  push:

  # Allows manual running of the action.
  workflow_dispatch:

jobs:
  build-i686-debug:
    runs-on: ubuntu-latest
    container:
      image: kevincharm/i686-elf-gcc-toolchain
      env:
        DOWNLOAD_GCC: gcc-8.1.0
    steps:
      - name: Cache dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ninja-build clang-tidy
          version: 1.0
          execute_install_scripts: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure and build
        uses: threeal/cmake-action@latest
        with:
          args: -DCMAKE_BUILD_TYPE:STRING=Debug -Dos_TARGET_TRIPLET=i686-pc-none-elf -DDos_ENABLE_TESTS=ON -Dos_ENABLE_IMAGE=ON
          generator: Ninja
          run-build: true
          run-test: true
